
// POSTS

export const POSTS_GET_REQUEST ='POSTS_GET_REQUEST';
export const POSTS_GET_SUCCESS ='POSTS_GET_SUCCESS';
export const POSTS_GET_ERROR ='POSTS_GET_ERROR';
export const POSTS_SEARCH = 'POSTS_SEARCH';
export const POSTS_CURRENT_PAGE = 'POSTS_CURRENT_PAGE';


export const POSTS_LOADED = 'POSTS_LOADED';
export const POSTS_SORT = 'POSTS_SORT';

// export const POSTS_SEARCH = 'POSTS_SEARCH';